version: '3'
services:

  pg:
    container_name: pg
    image: postgres:14
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    restart: always
    ports:
      - 5432:5432
    
volumes:
  pg_data:
