version: "3"
services:
  pg:
    image: postgres:14
    container_name: pg

    environment:
      - POSTGRES_PASSWORD=pg418890
    ports:
      - 5432:5432
  pgbouncer:
    image: bitnami/pgbouncer
    container_name: pgbouncer
    environment:
      - POSTGRESQL_PASSWORD=pg418890
      - POSTGRESQL_HOST=pg
    ports:
      - 6432:6432

