version: '3'
services:

  pg:
    container_name: pg
    image: postgres:14
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env

  backend:
    container_name: faback
    depends_on:
      - pg
    env_file:
      - .env
    build:
      context: backend
      dockerfile: backend.dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}

volumes:
  pg_data:
