"""empty message

Revision ID: 11c1e16e9bcc
Revises: 9350d8ff6532
Create Date: 2022-10-01 10:03:46.732199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11c1e16e9bcc'
down_revision = '9350d8ff6532'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
