"""fix one-to-one

Revision ID: 6416e10cbbe5
Revises: 84d83d3a8eab
Create Date: 2022-09-03 23:43:42.156836

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6416e10cbbe5"
down_revision = "84d83d3a8eab"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
