"""move full name to profile model

Revision ID: d23a11992020
Revises: 6416e10cbbe5
Create Date: 2022-09-07 15:07:00.560321

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d23a11992020"
down_revision = "6416e10cbbe5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_app_user_full_name", table_name="app_user")
    op.drop_column("app_user", "full_name")
    op.add_column(
        "profile", sa.Column("full_name", sa.String(), nullable=True)
    )
    op.create_index(
        op.f("ix_profile_full_name"), "profile", ["full_name"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_profile_full_name"), table_name="profile")
    op.drop_column("profile", "full_name")
    op.add_column(
        "app_user",
        sa.Column(
            "full_name", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
    )
    op.create_index(
        "ix_app_user_full_name", "app_user", ["full_name"], unique=False
    )
    # ### end Alembic commands ###
